project:
  type: website

website:
  title: "Fedor V. Gerasimov"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: contents/research/research.qmd
        text: Research
      # - href: talks.qmd
      #   text: Talks
      - href: contents/teaching/teaching.qmd
        text: Teaching
      - href: contents/CV/CV.qmd
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true